version: "1"
services:
  front:
    container_name: "travel-client"
    build:
      context: ../
      dockerfile: travelWebDocker/Dockerfile
    ports:
      - "4032:3000"
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ../project:/project
      - /project/node_modules
      - /project/.next
    stdin_open: true
    tty: true
